"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-28 20:04:38.830317
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_mtime", sa.Double(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("artist", sa.Text(), nullable=True),
        sa.Column("album", sa.Text(), nullable=True),
        sa.Column("duration_s", sa.Double(), nullable=True),
        sa.Column("isrc", sa.String(length=15), nullable=True),
        sa.Column("mb_recording_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tracks_content_hash"), ["content_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_tracks_status"), ["status"], unique=False)

    op.create_table(
        "analyses",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("pipeline_version", sa.String(length=32), nullable=False),
        sa.Column("valence", sa.Double(), nullable=False),
        sa.Column("arousal", sa.Double(), nullable=False),
        sa.Column("bpm", sa.Double(), nullable=True),
        sa.Column("key", sa.String(length=4), nullable=True),
        sa.Column("scale", sa.String(length=8), nullable=True),
        sa.Column("loudness_lufs", sa.Double(), nullable=True),
        sa.Column("mood_probs", sa.JSON(), nullable=False),
        sa.Column("tag_probs", sa.JSON(), nullable=False),
        sa.Column("top_tags", sa.Text(), nullable=False),
        sa.Column("features_2007", sa.JSON(), nullable=True),
        sa.Column("octant_2007", sa.String(length=16), nullable=True),
        sa.Column("hevner_2007", sa.String(length=16), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id"),
    )
    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analyses_pipeline_version"), ["pipeline_version"], unique=False
        )
        batch_op.create_index("ix_analyses_va", ["valence", "arousal"], unique=False)

    op.create_table(
        "embeddings",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=32), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("vector", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id", "model"),
    )
    op.create_table(
        "segments",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("start_s", sa.Double(), nullable=False),
        sa.Column("valence", sa.Double(), nullable=False),
        sa.Column("arousal", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id", "idx"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("segments")
    op.drop_table("embeddings")
    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.drop_index("ix_analyses_va")
        batch_op.drop_index(batch_op.f("ix_analyses_pipeline_version"))

    op.drop_table("analyses")
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracks_status"))
        batch_op.drop_index(batch_op.f("ix_tracks_content_hash"))

    op.drop_table("tracks")
    op.drop_table("jobs")
    # ### end Alembic commands ###
